// ============================================================================
// @terminal/shared - Main Entry Point
// ============================================================================

// Channels
export {
  CHANNEL_PREFIX,
  type ChannelPrefix,
  getTn3270InputChannel,
  getTn3270OutputChannel,
  getTn3270ControlChannel,
  getGatewayControlChannel,
  getSessionsChannel,
  parseChannel,
} from './channels';

// Messages
export {
  type MessageType,
  type Encoding,
  type TerminalType,
  type DataMessage,
  type ResizeMessage,
  type ResizeMeta,
  type PingMessage,
  type PongMessage,
  type ErrorMessage,
  type ErrorMeta,
  type SessionCreateMessage,
  type SessionCreateMeta,
  type SessionDestroyMessage,
  type SessionCreatedMessage,
  type SessionCreatedMeta,
  type SessionDestroyedMessage,
  type SessionDestroyedMeta,
  type TN3270Field,
  type TN3270ScreenMeta,
  type TN3270ScreenMessage,
  type TN3270CursorMeta,
  type TN3270CursorMessage,
  type ASTStatusType,
  type ASTRunMeta,
  type ASTRunMessage,
  type ASTControlAction,
  type ASTControlMeta,
  type ASTControlMessage,
  type ASTPausedMeta,
  type ASTPausedMessage,
  type ASTStatusMeta,
  type ASTStatusMessage,
  type ASTProgressMeta,
  type ASTProgressMessage,
  type ASTItemResultMeta,
  type ASTItemResultMessage,
  type MessageEnvelope,
  isDataMessage,
  isResizeMessage,
  isPingMessage,
  isPongMessage,
  isErrorMessage,
  isSessionCreateMessage,
  isSessionDestroyMessage,
  isSessionCreatedMessage,
  isSessionDestroyedMessage,
  isTN3270ScreenMessage,
  isTN3270CursorMessage,
  isASTRunMessage,
  isASTControlMessage,
  isASTStatusMessage,
  isASTPausedMessage,
  isASTProgressMessage,
  isASTItemResultMessage,
  resetSequence,
  createDataMessage,
  createResizeMessage,
  createPingMessage,
  createPongMessage,
  createErrorMessage,
  createSessionCreateMessage,
  createSessionDestroyMessage,
  createSessionCreatedMessage,
  createSessionDestroyedMessage,
  createTN3270ScreenMessage,
  createTN3270CursorMessage,
  createASTRunMessage,
  createASTControlMessage,
  createASTStatusMessage,
  createASTProgressMessage,
  createASTItemResultMessage,
  serializeMessage,
  deserializeMessage,
} from './messages';

// Errors
export {
  ERROR_CODES,
  type ErrorCode,
  TerminalError,
  type TerminalErrorOptions,
  getErrorMessage,
  type ErrorResponse,
  type SuccessResponse,
  type ApiResponse,
  createErrorResponse,
  createSuccessResponse,
  isErrorResponse,
  isSuccessResponse,
} from './errors';

// Auth
export {
  type User,
  type UserSession,
  type AuthTokenPayload,
  isValidEmail,
} from './auth';

// Config
export {
  type ServerConfig,
  type ValkeyConfig,
  type AuthConfig,
  type TN3270Config,
  type AppConfig,
  DEFAULT_SERVER_CONFIG,
  DEFAULT_VALKEY_CONFIG,
  DEFAULT_AUTH_CONFIG,
  DEFAULT_TN3270_CONFIG,
  getDefaultConfig,
} from './config';

// Utils
export {
  generateSessionId,
  generateUserId,
  now,
  sleep,
  retry,
  clamp,
  debounce,
  throttle,
  safeJsonParse,
  base64Encode,
  base64Decode,
} from './utils';
